### PR TITLE
Update WASI thread proposal tests in CI

### PR DESCRIPTION
**Pull request by eloparco**
Update CI to run extended WASI threads tests included in the proposal https://github.com/WebAssembly/wasi-testsuite/tree/prod/testsuite-all/tests/proposals/wasi-threads

### CODE REVIEW

**Comment by eloparco** [comment]
As expected the CI is currently failing, we need to complete and merge #1975 to make the WASI proposal tests pass.

**Comment by eloparco** [comment]
Do we want to keep this one? 
https://github.com/bytecodealliance/wasm-micro-runtime/blob/38c67b3f4815a628ce0f9bc22186bface4678089/tests/wamr-test-suites/test_wamr.sh#L463
I don't see it used anywhere and I couldn't find the `wasi_test.py` file referenced there.

**Comment by loganek** [comment]
> Do we want to keep this one?
> 
> https://github.com/bytecodealliance/wasm-micro-runtime/blob/38c67b3f4815a628ce0f9bc22186bface4678089/tests/wamr-test-suites/test_wamr.sh#L463
> 
> 
> I don't see it used anywhere and I couldn't find the `wasi_test.py` file referenced there.

I think it's being used here: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/tests/wamr-test-suites/test_wamr.sh#L751

**Review by loganek — COMMENTED** [review]
LGTM

**Review by loganek — APPROVED** [review]

**Comment by eloparco** [comment]
> I think it's being used here: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/tests/wamr-test-suites/test_wamr.sh#L751

But they're not executed in the CI. And if I try to run them locally I see that it tries to use a `wasi_test.py` file that is not there. If they're obsolete I think we can remove them.

**Comment by loganek** [comment]
> > I think it's being used here: [`main`/tests/wamr-test-suites/test_wamr.sh#L751](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/tests/wamr-test-suites/test_wamr.sh?rgh-link-date=2023-02-24T16%3A24%3A34Z#L751)
> 
> But they're not executed in the CI. And if I try to run them locally I see that it tries to use a `wasi_test.py` file that is not there. If they're obsolete I think we can remove them.

I'm not 100% sure but IIRC Intel runs wasi tests in their internal pipelines. But I agree, if they're not runnable from this repository, we probably should move it out.

**Comment by eloparco** [comment]
I tried running locally the test that is failing in the CI and sometimes (not always, suggesting a race condition) I see the same error. I created a PR to fix it #1991

**Review by wenyongh — COMMENTED** [review]
LGTM

**Comment by eloparco** [comment]
> Is this PR a counterpart of https://github.com/bytecodealliance/wasm-micro-runtime/pull/1963? Is https://github.com/bytecodealliance/wasm-micro-runtime/pull/1963 still needed?

#1963 is still needed since it adds some additional tests to check for some other behaviors.

**Pull request merged**
