### PR TITLE
GlobalValueSet was moved to IRPartitionLayer recently, but we have a …

### PR DESCRIPTION
**Pull request by sjamesr**
…local definition anyway

### CODE REVIEW

**Comment by sjamesr** [comment]
This resolves a compilation error against recent revisions of LLVM

**Comment by lum1n0us** [comment]
> GlobalValueSet was moved to IRPartitionLayer recently

In which llvm release? WAMR is somewhat sensitive to the version of LLVM. Currently WAMR depends on LLVM 15.x

**Comment by sjamesr** [comment]
It was moved about a month ago in https://github.com/llvm/llvm-project/commit/04af63b267c391a4b0a0fb61060f724f8b5bc2be. Internally at Google we build WAMR against LLVM at approximately HEAD.

In the above change, GlobalValueSet is now `using GlobalValueSet = std::set<const GlobalValue *>;` inside `IRPartitionLayer`.

I think my change is safe, to my non-expert eyes the definition of GlobalValueSet is the same before and after this change.

**Review by lum1n0us — APPROVED** [review]
LGTM

**Pull request merged**
