### PR TITLE
Update version to 2.1.0

### PR DESCRIPTION
**Pull request by loganek**
There was quite a few enchancements since 2.0.0 release and I think it'd be good to have another release now. If there are no objections, I'll update the release notes sections, so please let me know.

### CODE REVIEW

**Comment by wenyongh** [comment]
> There was quite a few enchancements since 2.0.0 release and I think it'd be good to have another release now. If there are no objections, I'll update the release notes sections, so please let me know.

@loganek thanks a lot, it is good to me, had better update the release notes after several other PRs are merged. Currently there are CI failures and we are looking into them.

**Comment by wenyongh** [comment]
@loganek I have merged most of the available PRs to main branch, maybe you can help update the release notes of this PR? And we can do more tests before releasing WAMR-2.1.0.

BTW, @yzha107 from our team submitted PR #3490 to open sourcing the unit test cases, and moved the files under the original `tests/unit` to folder `tests/unit/tid-allocator` as a sub case of unit test, could you also help have a look? Thanks.

**Comment by loganek** [comment]
@wenyongh I just rebased this PR on top of the main branch and updated the release notes. Also, I'll look at the unit tests PR - thanks a lot for open sourcing it.

**Comment by wenyongh** [comment]
@loganek I have merged the unit test PR and fixed the CI issue (#3490, #3499), could you rebase and update the release notes?  And BTW I added a comment for this PR. I think we can merge this PR after you update the release notes and then do more test, and if things go well, we can create the release.

**Comment by loganek** [comment]
@wenyongh just rebased and updated the commit, should be ready for merging.

**Review by wenyongh — APPROVED** [review]
LGTM

**Comment by wenyongh** [comment]
@loganek FYI, WAMR-2.1.0 release was created successfully:
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-2.1.0

**Pull request merged**
