### PR TITLE
CI: Update version of checkout to supress warnings

### PR DESCRIPTION
**Pull request by no1wudi**
Fix:
image

### CODE REVIEW

**Comment by no1wudi** [comment]
@wenyongh Yhe base image of "build_iwasm_linux_gcc4_8" (ubuntu 14.04) is too old and incompatible with nodejs 20. Can it be upgraded to a newer version while installing an older version of GCC 4.8 to solve this problem? In the long term, tools that have reached their end of life should not be available in CI.

**Comment by wenyongh** [comment]
> @wenyongh The base image of "build_iwasm_linux_gcc4_8" (ubuntu 14.04) is too old and incompatible with nodejs 20. Can it be upgraded to a newer version while installing an older version of GCC 4.8 to solve this problem? In the long term, tools that have reached their end of life should not be available in CI.
> 
> ```
> Run actions/checkout@v4
> /usr/bin/docker exec  fe985570b9da95f4b2ffecabc0a690638b490e6aa6b5439c2ae88accee20[29](https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/7665780571/job/20892822021?pr=3093#step:3:30)b6 sh -c "cat /etc/*release | grep ^ID"
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
> /__e/node20/bin/node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
> /__e/node20/bin/node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
> /__e/node20/bin/node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
> ```

Hi, I have no idea about that, the gcc-4.8 was added by @loganek, maybe he can help have a look.

**Comment by no1wudi** [comment]
Leave it to v3 for now, please notice this work flow will fail some day @loganek 

https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/7666215923

**Comment by loganek** [comment]
Hi,
Yes, we've added it as we have some of the usecases to support such old compilers. IIRC installing gcc 4.8 on newer ubuntu machines was not straightforward; I'd suggest keeping the image for as long as it isn't a blocker; once this really starts blocking any development, we can delete the build.

**Comment by no1wudi** [comment]
>  I'd suggest keeping the image for as long as it isn't a blocker; once this really starts blocking any development, we can delete the build.

I guess it's OK

**Review by wenyongh — APPROVED** [review]

**Pull request merged**
