### PR TITLE
Move wasm_runtime_destroy_wasi and wasi_nn_destroy calls together

### PR DESCRIPTION
**Pull request by yamt**
This is a preparation to introduce a generic "host cleanup" hook.

While the comment on wasm_runtime_destroy_wasi calls seems saying that the cleanup process can rely on the app heap,

- I couldn't find it in the current implementations.

- For sandboxing reasons, the cleanup logic (or any natively-executed logic in general) should not rely on app heap, which is owned by the module itself.

### CODE REVIEW

**Comment by yamt** [comment]
> I couldn't find it in the current implementations.

@wenyongh 
do you have any idea?
as you added the comment in commit 46b93b9d229e0f8e6a08248f800b1d70497e95d1

**Comment by wenyongh** [comment]
> > I couldn't find it in the current implementations.
> 
> @wenyongh do you have any idea? as you added the comment in commit [46b93b9](https://github.com/bytecodealliance/wasm-micro-runtime/commit/46b93b9d229e0f8e6a08248f800b1d70497e95d1)

@yamt The comment is obsolete, sorry to make the confusion. We had changed `module_malloc` to `wasm_runtime_malloc` in libc_wasi_wrapper.c in the PR below and I forgot to remove the comment:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/481

See the changes in libc_wasi_wrapper.c:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/481/files#diff-18a1c12794da572224835cdd9491ff7f93bc7ff81249c75ead3052e7f815f9f8

It doesn't rely on app heap again and this PR seems to be good.

**Comment by yamt** [comment]
> @yamt The comment is obsolete, sorry to make the confusion. We had changed `module_malloc` to `wasm_runtime_malloc` in libc_wasi_wrapper.c in the PR below and I forgot to remove the comment: #481
> 
> See the changes in libc_wasi_wrapper.c: https://github.com/bytecodealliance/wasm-micro-runtime/pull/481/files#diff-18a1c12794da572224835cdd9491ff7f93bc7ff81249c75ead3052e7f815f9f8

thank you.
but these iovec alloctions seem all temporary within the functions.
they can't affect wasm_runtime_destroy_wasi anyway, can they?

**Comment by wenyongh** [comment]
> > @yamt The comment is obsolete, sorry to make the confusion. We had changed `module_malloc` to `wasm_runtime_malloc` in libc_wasi_wrapper.c in the PR below and I forgot to remove the comment: #481
> > See the changes in libc_wasi_wrapper.c: https://github.com/bytecodealliance/wasm-micro-runtime/pull/481/files#diff-18a1c12794da572224835cdd9491ff7f93bc7ff81249c75ead3052e7f815f9f8
> 
> thank you. but these iovec alloctions seem all temporary within the functions. they can't affect wasm_runtime_destroy_wasi anyway, can they?

This PR changed the memory allocation for wasi_ctx's fields from wasm_runtime_module_malloc to wasm_runtime_malloc:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/455/files#diff-bfd0d83ff0f2d993326c15717688c3abb59d6f2384044769168b4316e0b6ea0b

**Comment by yamt** [comment]
> > > @yamt The comment is obsolete, sorry to make the confusion. We had changed `module_malloc` to `wasm_runtime_malloc` in libc_wasi_wrapper.c in the PR below and I forgot to remove the comment: #481
> > > See the changes in libc_wasi_wrapper.c: https://github.com/bytecodealliance/wasm-micro-runtime/pull/481/files#diff-18a1c12794da572224835cdd9491ff7f93bc7ff81249c75ead3052e7f815f9f8
> > 
> > 
> > thank you. but these iovec alloctions seem all temporary within the functions. they can't affect wasm_runtime_destroy_wasi anyway, can they?
> 
> This PR changed the memory allocation for wasi_ctx's fields from wasm_runtime_module_malloc to wasm_runtime_malloc: https://github.com/bytecodealliance/wasm-micro-runtime/pull/455/files#diff-bfd0d83ff0f2d993326c15717688c3abb59d6f2384044769168b4316e0b6ea0b

thank you. it makes sense.

**Review by wenyongh — APPROVED** [review]
LGTM

**Pull request merged**
