### PR TITLE
Refine looking up aot function with index

### PR DESCRIPTION
**Pull request by wenyongh**

### CODE REVIEW

**Comment by lum1n0us** [comment]
Is it because `DefPointer(WASMExportFuncInstance *, export_functions);` now are sorted by names instead of function indexes?

**Comment by wenyongh** [comment]
> Is it because `DefPointer(WASMExportFuncInstance *, export_functions);` now are sorted by names instead of function indexes?

No, event if the export_functions isn't sorted by names, it doesn't mean that it will be sorted by function index, it's in random order. This PR's optimization is suitable no matter whether export_functions is sorted by names or not.

**Comment by lum1n0us** [comment]
Totally true. It sticks to the order given by the export section context, which is based on toolchains and seems random now.

So, we now need to sort the list `export_functions` by name and store them in that order, and then search by both name and function index.

**Comment by wenyongh** [comment]
> Totally true. It sticks to the order given by the export section context, which is based on toolchains and seems random now.
> 
> So, we now need to sort the list `export_functions` by name and store them in that order, and then search by both name and function index.

Yes, sort `export_functions` by name, and create another map array whose element is `<func_idx, export_ith>` and sort the array by func_idx.

**Review by lum1n0us — APPROVED** [review]
LGTM

**Review by xujuntwt95329 — APPROVED** [review]
LGTM

**Pull request merged**
