### PR TITLE
Update version to 2.2.0

### PR DESCRIPTION
**Pull request by Zzzabiyaka**
Hi everyone! 

I am proposing to release a new version of WAMR to benefit from the various changes merged recently 

It has been a great pleasure preparing the release notes and noticing how much we all were able to do just in a couple of months to improve the runtime!

I bumped only patch version so far, please let me know if we should consider bumping minor instead 

@wenyongh, @loganek and other owners, could you please take a look at the release notes to check that the commits distribution between new features / fixes etc looks good to you.

I also ignored all the commits when main was merged into some other branch.

Thank you

### CODE REVIEW

**Comment by wenyongh** [comment]
@Zzzabiyaka thanks for the reminding! We are planning to release a new version recently, hope that we can start it after several PRs are merged. And I think the version number should be 2.2.0, since we had imported some new important features: multi-memory for classic interpreter, table64, shared heap and so on, see [semantic_version.md](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/semantic_version.md). So could you help change it?

**Comment by Zzzabiyaka** [comment]
Hi @wenyongh ,

Sure will do that

**Comment by wenyongh** [comment]
@Zzzabiyaka I confirmed with @TianlongLiang and @lum1n0us, all the left PRs for the releasing have been merged, could you update the release notes so that we can do more tests and then release 2.2.0? Thanks.

**Review by wenyongh — APPROVED** [review]

**Review by lum1n0us — APPROVED** [review]
LGTM

**Pull request merged**
