### PR TITLE
Merge main into dev/wasi-libc-windows

### PR DESCRIPTION
**Pull request by loganek**

### CODE REVIEW

**Comment by loganek** [comment]
@wenyongh I've opened the PR so you can see how to resolve conflicts. Would you be able to merge main to `dev/wasi-libc-windows` based on that? Many thanks

Also, I had to revert a change introduced to wasm_application.c in the https://github.com/bytecodealliance/wasm-micro-runtime/pull/2655 as it was breaking the execution of spec tests. I'm not actually sure how do the spec tests work now on linux and other platforms as it didn't print the exception message in the repl mode. I didn't spend too much time investigating that though; unless you know on top of your head what can be wrong, I'd suggest moving ahead with that and look into it later.

**Comment by wenyongh** [comment]
> @wenyongh I've opened the PR so you can see how to resolve conflicts. Would you be able to merge main to `dev/wasi-libc-windows` based on that? Many thanks
> 

Sure, I will try to resolve the conflicts and merge branch main into dev/wasi-libc-windows based on this PR tomorrow.

> Also, I had to revert a change introduced to wasm_application.c in the #2655 as it was breaking the execution of spec tests. I'm not actually sure how do the spec tests work now on linux and other platforms as it didn't print the exception message in the repl mode. I didn't spend too much time investigating that though; unless you know on top of your head what can be wrong, I'd suggest moving ahead with that and look into it later.

I guess it is caused by exception isn't printed in `iwasm --repl` mode introduced by #2655. I fixed it #2734:
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2734/commits/b2ac48983dec31cc95565993f29929c7b0f21037

**Comment by wenyongh** [comment]
@loganek Welcome, I have merged branch main into dev/wasi-libc-windows, just based on your local branch and restored the changes in wasm_application.c. Since PR #2734 had been merged into main and then was synchronized to branch dev/wasi-lib-windows, the CIs ran successfully. See:

https://github.com/bytecodealliance/wasm-micro-runtime/commit/20f1a8c86c3a38e0faa7b3178642f0f4a791c430
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/6806666581
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/6806666571

**Comment by loganek** [comment]
Thank you

**Pull request closed without merging**
