### PR TITLE
Fix compilation error found in tflite test

### PR DESCRIPTION
**Pull request by lum1n0us**

### CODE REVIEW

**Comment by rodjjo** [comment]
Is your example compiling even with this typo here ?
[wasm_nn_error instead of wasi_nn_error](https://github.com/bytecodealliance/wasm-micro-runtime/blob/438b81bd04a64c79d11457923d46f08c8da9313b/core/iwasm/libraries/wasi-nn/test/utils.c#L60)

How about the [load](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/libraries/wasi-nn/test/utils.c#L49) function here, are we suppose to include `#include "wasi_nn.h"` in `utils.c` as it is declared there ?

Did you get problem with the `requirements.txt` related to numpy version ? 
I was only able to install `numpy==1.24.4` 

In order to test your branch i had to change:
image

Then I used these commands (a bit modified from your Readme.md file):
```bash
#!/bin/bash
export EXECUTION_TYPE=cpu 

# Build the runtime
docker build -t wasi-nn-${EXECUTION_TYPE} -f core/iwasm/libraries/wasi-nn/test/Dockerfile.${EXECUTION_TYPE} . || exit 1

# Build wasm app
docker build -t wasi-nn-compile -f core/iwasm/libraries/wasi-nn/test/Dockerfile.compile . || exit 1

 docker run \
     -w /wasi-nn/core/iwasm/libraries/wasi-nn/test \
     -v $PWD/:/wasi-nn \
     -v $PWD/core/iwasm/libraries/wasi-nn/test/models:/models \
     wasi-nn-compile \
     --dir=/ \
     --env="TARGET=cpu" || exit 1

# Run wasm app
docker run \
    -v $PWD/core/iwasm/libraries/wasi-nn/test:/assets \
    -v $PWD/core/iwasm/libraries/wasi-nn/test/models:/models \
    wasi-nn-cpu \
    --dir=/ \
    --env="TARGET=cpu" \
    /assets/test_tensorflow.wasm
```

After doing that I got:
image


So yes to your question [here](https://github.com/bytecodealliance/wasm-micro-runtime/pull/3817): 
It's not necessary `--native-lib` anymore. Thank you for updating the readme files.

**Comment by lum1n0us** [comment]
> Is your example compiling even with this typo here ?
[wasm_nn_error instead of wasi_nn_error](https://github.com/bytecodealliance/wasm-micro-runtime/blob/438b81bd04a64c79d11457923d46f08c8da9313b/core/iwasm/libraries/wasi-nn/test/utils.c#L60)

Sure. I will include it in this PR.

**Comment by lum1n0us** [comment]
> Did you get problem with the requirements.txt related to numpy version ?
I was only able to install numpy==1.24.4

Yes. I met the problem when using *1.26.4*. I will include it in this PR

**Comment by lum1n0us** [comment]
> How about the [load](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/libraries/wasi-nn/test/utils.c#L49) function here, are we suppose to include #include "wasi_nn.h" in utils.c as it is declared there ?

Sure. I will include it in this PR.

**Review by wenyongh — APPROVED** [review]

**Comment by lum1n0us** [comment]
I've made some changes. Now the result will look like this.

```
[test_tensorflow.c:130 INFO] ################### Testing sum...
[wasi_nn.c:269 WARNING] load_by_name_with_config() not found
[wasi_nn_tensorflowlite.cpp:276 WARNING] Default encoding is CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[test_tensorflow.c:132 INFO] ################### Testing max...
[wasi_nn_tensorflowlite.cpp:276 WARNING] Default encoding is CPU.
[test_tensorflow.c:45 INFO] Result: max is 24.000000
[test_tensorflow.c:134 INFO] ################### Testing average...
[wasi_nn_tensorflowlite.cpp:276 WARNING] Default encoding is CPU.
[test_tensorflow.c:64 INFO] Result: average is 12.000000
[test_tensorflow.c:136 INFO] ################### Testing multiple dimensions...
[wasi_nn_tensorflowlite.cpp:276 WARNING] Default encoding is CPU.
[test_tensorflow.c:138 INFO] ################### Testing multiple outputs...
[wasi_nn_tensorflowlite.cpp:276 WARNING] Default encoding is CPU.
[test_tensorflow.c:141 INFO] Tests: passed!
```

**Review by xujuntwt95329 — APPROVED** [review]

**Pull request merged**
