### PR TITLE
WAMR 1.2.4

### PR DESCRIPTION
**Pull request by g0djan**
Plenty fixes have been merged in last months.
Would you consider doing a new release @wenyongh @yamt ?

### CODE REVIEW

**Comment by wenyongh** [comment]
> Plenty fixes have been merged in last months. Would you consider doing a new release @wenyongh @yamt ?

Yes, I think we had better create a new release recently, before that we will try to fix several issues left and do more tests after merging dev/wasi-libc-windows.

**Comment by zoraaver** [comment]
> do more tests after merging dev/wasi-libc-windows.
@wenyongh I was just wondering what testing you're doing for windows and if there's a rough estimate for that? Many thanks

**Comment by wenyongh** [comment]
> i'm not aware of release-blocking issues.

Hi, some issues may be not so important or blocking, but I think we had better resolve them if we can or confirm what the issue is:
- for #2759, I have submitted #2765 to fix it
- to check #2755
- to check #2760, seems that @hasheddan is fixing it
- to support more targets for the release wamrc binary, as requested in https://github.com/bytecodealliance/wasm-micro-runtime/issues/2504
- to update tensorflow workload, which is nearly finished by PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/2369, need to check whether we can support the multi-threading. It is requested in https://github.com/bytecodealliance/wasm-micro-runtime/issues/2351

**Comment by wenyongh** [comment]
> > do more tests after merging dev/wasi-libc-windows.
> 
> @wenyongh I was just wondering what testing you're doing for windows (or needs to be done) and if there's a rough estimate for that? Many thanks

Hi, since the spec test scripts haven't been enabled in Windows platform, normally we just tested some standalone cases manually.

**Comment by lum1n0us** [comment]
> i'm not aware of release-blocking issues.

@yamt Have to say, there is a problem we have concerns. 
https://github.com/bytecodealliance/wasm-micro-runtime/issues/2773

**Comment by yamt** [comment]
> > i'm not aware of release-blocking issues.
> 
> @yamt Have to say, there is a problem we have concerns. #2773

while it's an interesting issue, it isn't a new problem, and thus not a release blocker, IMO.

**Comment by g0djan** [comment]
A data race seems important to me https://github.com/bytecodealliance/wasm-micro-runtime/issues/2804

**Comment by g0djan** [comment]
> to support more targets for the release wamrc binary, as requested in https://github.com/bytecodealliance/wasm-micro-runtime/issues/2504

Is it fixed?

> to update tensorflow workload, which is nearly finished by PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/2369, need to check whether we can support the multi-threading. It is requested in https://github.com/bytecodealliance/wasm-micro-runtime/issues/2351

Pinged the author in the ticket, but seems he wasn't active in the issue almost 2 months by now

**Comment by wenyongh** [comment]
> > to support more targets for the release wamrc binary, as requested in #2504
> 
> Is it fixed?

Yes, we submitted #2778 to fix it, and will check again when creating the release binaries.

> 
> > to update tensorflow workload, which is nearly finished by PR #2369, need to check whether we can support the multi-threading. It is requested in #2351
> 
> Pinged the author in the ticket, but seems he wasn't active in the issue almost 2 months by now

Supporting multi-threading requires more time and effort as expected, I think we had better go ahead and not wait for it. I will create another PR to update the release notes first, and try to fix #2804 and check whether there are other issues to fix, and if all is OK, then we can create the new release.

**Comment by g0djan** [comment]
Closed in favor of https://github.com/bytecodealliance/wasm-micro-runtime/pull/2821

**Comment by wenyongh** [comment]
@g0djan The WAMR-1.3.0 release was created:
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.0

**Pull request closed without merging**
