### PR TITLE
wamr-test-suites/test_wamr.sh: add an option to specify wamrc binary

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by HongxiaWangSSSS** [comment]
Hi yamt-san,
I'd like to know why use external wamrc in ci? Sometimes using the wrong version of wamrc may also cause the test to fail,  like aot in different formats, unsolved issues. 
Maybe the wamrc generated using the current version better reflects the accuracy of the test.
If it is about the xtensa platform, I prefer according the platform build different [wamrc](https://github.com/bytecodealliance/wasm-micro-runtime/blob/8af155076c6c62d9766ede640cf3f29fa73a4b53/tests/wamr-test-suites/test_wamr.sh#L797C1-L797C23) in the current wamr.

**Comment by yamt** [comment]
> I'd like to know why use external wamrc in ci?

i occasionally run this script locally and i often have a wamrc binary to use.

**Review by wenyongh — APPROVED** [review]
LGTM

**Review by lum1n0us — APPROVED** [review]
LGTM

**Pull request merged**
