### PR TITLE
fix dockerfile linter warnings

### PR DESCRIPTION
**Pull request by TianlongLiang**
Should we also consider adding a CI that uses hadolint to check Dockerfile?

### CODE REVIEW

**Comment by yamt** [comment]
is "replace curl with wget" change a recommendation from hadolint?
do you still need to install curl after the change?
i feel a little sad because i personally prefer curl over wget. :-)

**Comment by TianlongLiang** [comment]
Yes, it's a [warning](https://github.com/hadolint/hadolint/wiki/DL4001) in the hadolint.
Since it's a devdocker, I think maybe should keep it installed in case anyone wants to use curl inside the container.

**Comment by wenyongh** [comment]
Hi @tonibofarull, this PR changes some docker file of wasi-nn, could you help check whether it is good to you? Thanks.

**Review by tonibofarull — APPROVED** [review]

**Review by wenyongh — COMMENTED** [review]
LGTM

**Pull request merged**
