### PR TITLE
fixed minor typos in coding guidelines workflow

### PR DESCRIPTION
**Pull request by hritikgupta**

### CODE REVIEW

**Review by loganek — APPROVED** [review]

**Review by lum1n0us — APPROVED** [review]
LGTM

**Comment by hritikgupta** [comment]
fails at install SGX SDK step (this seems intermittent), is there a way to re-trigger?

**Comment by wenyongh** [comment]
There is a typo in the renamed file name `coding_guildelines.yml`, could you change to `coding_guidelines.yml`?

**Comment by hritikgupta** [comment]
> There is a typo in the renamed file name `coding_guildelines.yml`, could you help change to `coding_guidelines.yml`?

ah missed that, done!

**Review by loganek — APPROVED** [review]

**Pull request merged**
