### PR TITLE
Dev/exce handling - Initial Contribution for Exception Handling (Issue #1884)

### PR DESCRIPTION
**Pull request by woodsmc**
### Included in this contribution
**NB:** This is an initial contribution, part 1 of 2 contributions. 
* Inside the classic interpreter only:
  * Initial handling of Tags
  * Initial handling of Exceptions based on W3C Exception Proposal (note this isn't a direct copy of traditional C++ exceptions)
* Builds with no-regressions

### To be included in Part 2
* Bug fixes and naming convention improvements
* Additional CI /CD changes to validate ENABLE_EXCE_HANDLING switch builds ok all platforms
* Import and Export of Exceptions and Tags

### CODE REVIEW

**Comment by woodsmc** [comment]
I don't see any coding guideline failures on the forked branch after push e1c61e7. I'd love any advice on how I can validate that the contributions follow coding guidelines and correct any issue offline.

**Comment by lum1n0us** [comment]
```
$ git-clang-format-12 --binary $(which clang-format-12) --style file --extensions c,cpp,h -v --diff f5588872 HEAD

diff --git a/core/iwasm/interpreter/wasm_interp_classic.c b/core/iwasm/interpreter/wasm_interp_classic.c
index 85c6c301..56720b56 100644
--- a/core/iwasm/interpreter/wasm_interp_classic.c
+++ b/core/iwasm/interpreter/wasm_interp_classic.c
@@ -1780,17 +1780,18 @@ wasm_interp_call_func_bytecode(WASMModuleInstance *module,
                 HANDLE_OP_END();
             }
 #else
-    HANDLE_OP(WASM_OP_UNUSED_0x06)
-    HANDLE_OP(WASM_OP_UNUSED_0x07)
-    HANDLE_OP(WASM_OP_UNUSED_0x08)
-    HANDLE_OP(WASM_OP_UNUSED_0x09)
-    HANDLE_OP(WASM_OP_UNUSED_0x18)
-    HANDLE_OP(WASM_OP_UNUSED_0x19)
-    {
-        wasm_set_exception(module, "exception handling opcode not implemented");
-        /* that "exception" is the trap */
-        goto got_exception;
-    }
+            HANDLE_OP(WASM_OP_UNUSED_0x06)
+            HANDLE_OP(WASM_OP_UNUSED_0x07)
+            HANDLE_OP(WASM_OP_UNUSED_0x08)
+            HANDLE_OP(WASM_OP_UNUSED_0x09)
+            HANDLE_OP(WASM_OP_UNUSED_0x18)
+            HANDLE_OP(WASM_OP_UNUSED_0x19)
+            {
+                wasm_set_exception(module,
+                                   "exception handling opcode not implemented");
+                /* that "exception" is the trap */
+                goto got_exception;
+            }

 #endif
             HANDLE_OP(EXT_OP_BLOCK)
```

**Comment by lum1n0us** [comment]
Since `git-clang-format` will go through all commits one by one in the whole PR, it may not work if using a new commit to fix older commits' style problems. One simple way is to squash all 20+ commits together.

**Comment by woodsmc** [comment]
Thanks folks. I'll close this PR and we will resubmit with a "squished" version. Thanks for the support - much appreciated.

**Pull request closed without merging**
