### PR TITLE
aot: Move stack_sizes table to a dedicated section

### PR DESCRIPTION
**Pull request by yamt**
To solve "AOT module load failed: resolve symbol stack_sizes failed" issue

Lightly tested on qemu armhf.

### CODE REVIEW

**Comment by yamt** [comment]
this fixes https://github.com/bytecodealliance/wasm-micro-runtime/issues/2312 partly

**Review by wenyongh — COMMENTED** [review]
LGTM

**Comment by wenyongh** [comment]
> this fixes #2312 partly

@yamt There is a conflicting file after I merged the PR #2313, could you resolve it so that I can merge this PR?

**Comment by yamt** [comment]
the last push is a conflict resolution

**Pull request merged**
