### PR TITLE
Refine Windows thread waiting list operations

### PR DESCRIPTION
**Pull request by wenyongh**
Add thread_wait_list_end node for thread data and cond for Windows platform
to speedup the thread join and cond wait operations: no need to traverse the
wait list to get the end node to append the wait node.

### CODE REVIEW

**Comment by loganek** [comment]
Could you clarify what's the problem and how the change solves it? I understand now that appending new node can be faster than before, but why was the slowness a problem at all (and was it really that slow)? I saw this issue https://github.com/bytecodealliance/wasm-micro-runtime/issues/1805 but still not clear to me what are we trying to achieve here. Thanks

**Comment by wenyongh** [comment]
> Could you clarify what's the problem and how the change solves it? I understand now that appending new node can be faster than before, but why was the slowness a problem at all (and was it really that slow)? I saw this issue #1805 but still not clear to me what are we trying to achieve here. Thanks

Here it is just to improve the performance, a defect of the original implementation is that it may be a little slow when traversing the list to get the end of the list (when the list is long):
```C
         /* Add to end of wait list */
        os_thread_wait_node *p = cond->thread_wait_list;
        while (p->next)
            p = p->next;
        p->next = node;
```
Using `thread_wait_list_end` to mark the end node of the list is to skip the searching since we can append the node to the end directly.

**Review by loganek — APPROVED** [review]
Ok, that's what I thought although I didn't expect that particular list can get so long it's even noticeable. 

LGTM.

**Comment by yamt** [comment]
i can understand the motivation to make the cond list a fifo.
however, for os_thread_data, it seems simpler to make it add a node to the head of the list.

**Comment by wenyongh** [comment]
> i can understand the motivation to make the cond list a fifo. however, for os_thread_data, it seems simpler to make it add a node to the head of the list.

Yes, refer to the pthread_join manual, "If multiple threads simultaneously try to join with the same thread, the results are undefined", so maybe we can do like you said. Here a consideration is that the first thread to join had better be notified first, or fifo.

**Pull request merged**
