### PR TITLE
Dev/wasi libc windows

### PR DESCRIPTION
**Pull request by loganek**
We propose merging the `dev/wasi-libc-windows` branch with it's current state. The implementation is already in a stage where it's possible to compile WAMR with wasi libc enabled and run wasi modules without errors. 

There's still quite a few wasi functions that are not implemented (mainly around filesystem, sockets and poll_oneoff) but I don't think that's a blocker and I suggest we continue development of that in the main branch (e.g. to avoid further merge conflicts). 

@wenyongh let me know what are your thoughts on this and if there's anything you'd like us to do before we merge the dev branch into main.

### CODE REVIEW

**Comment by loganek** [comment]
@wenyongh the build seems to fail due to reasons not related to the PR itself, I guess it might just be an interim github actions issue. The failing check is `compilation on windows-latest / test (classic-interp, $MULTI_MODULES_TEST_OPTIONS)` and I opened exactly the same PR in my fork: https://github.com/loganek/wasm-micro-runtime/pull/3 and the build is passing for this check: https://github.com/loganek/wasm-micro-runtime/actions/runs/6808240915/job/18512791839?pr=3 (and other checks too). Would you be able to restart the multimodule check? Thanks

**Comment by wenyongh** [comment]
> @wenyongh the build seems to fail due to reasons not related to the PR itself, I suspect it might just be an interim github actions issue. The failing check is `compilation on windows-latest / test (classic-interp, $MULTI_MODULES_TEST_OPTIONS)` and I opened exactly the same PR in my fork: [loganek#3](https://github.com/loganek/wasm-micro-runtime/pull/3) and the build is passing for this check: https://github.com/loganek/wasm-micro-runtime/actions/runs/6808240915/job/18512791839?pr=3 (and other checks too). Would you be able to restart the multimodule check? Thanks

Yes, I restarted it, now it runs successfully.

**Review by wenyongh — COMMENTED** [review]
LGTM

**Comment by wenyongh** [comment]
@loganek I have merged this PR since we have done carefully review in the
wasi-libc-windows development and it seems that there is no comments
added for this PR. Let's merge it, do more test and resolve issues if found.

**Comment by loganek** [comment]
Sounds good, thanks!

**Pull request merged**
