### PR TITLE
Implement Python language binding (#1192)

### PR DESCRIPTION
**Pull request by wenyongh**
Implement the first version of Python language binding

### CODE REVIEW

**Comment by lum1n0us** [comment]
Shall we keep it in a developed branch until finish the binary destruction?

**Comment by lum1n0us** [comment]
Shall we keep it in a developed branch until finish the binary destruction?

**Comment by wenyongh** [comment]
> Shall we keep it in a developed branch until finish the binary destruction?

Had better put it in the main branch, some developers may be eager to use it. And developer may not know the developed branch, and not sure when we can finish the binary release.

**Comment by lum1n0us** [comment]
OK. let's do it.

**Comment by lum1n0us** [comment]
OK. let's do it.

**Pull request merged**
