### PR TITLE
NuttX: Remove CONFIG_INTERPRETERS_WAMR_DISABLE_HW_BOUND_CHECK

### PR DESCRIPTION
**Pull request by yamt**
NuttX doen't have necessary functionalities for OS_ENABLE_HW_BOUND_CHECK. This config knob merely confuses users.

### CODE REVIEW

**Comment by no1wudi** [comment]
If this is confusing here, please add a comment to explain it instead of deleting it directly since:
1. It’s just a 1:1 mapping of the WAMR's config
2. We are trying to make hardware based bound check works on NuttX

**Comment by yamt** [comment]
> We are trying to make hardware based bound check works on NuttX

you are?
how?

**Comment by no1wudi** [comment]
Of course this feature need hardware support (MPU or MMU), there are more and more platform support the protected build or kernel build in NuttX, it's possible to implement hardware bounds check on them.

**Comment by yamt** [comment]
> Of course this feature need hardware support (MPU or MMU), there are more and more platform support the protected build or kernel build in NuttX, it's possible to implement hardware bounds check on them.

ok. good luck.

note that nuttx signal implementation is not compatible with how wamr uses it. you likely need to rewrite it too.
https://github.com/apache/nuttx/issues/10326

i will close this PR. it's ok for me to keep the option as far as someone aims to implement it.

**Pull request closed without merging**
