### PR TITLE
Vote for new nominated TSC members

### PR DESCRIPTION
**Pull request by xwang98**

### CODE REVIEW

**Comment by xwang98** [comment]
@donghengqaz, @loganek, @yamt: Could reply to this on whether or not you agree to accept the nomination?

@lum1n0us, @no1wudi, @qinxk-inter, @wei-tang, @wenyongh, @xujuntwt95329: As current TSC members, could you click emoji thumb up and thumb down for your vote?

**Comment by dongsheng28849455** [comment]
yes, I agree, thanks! that's my pleasure.

**Comment by loganek** [comment]
I'm accepting the nomination. Thanks a lot, looking forward to work with you.

**Comment by yamt** [comment]
i accept. thank you.

**Pull request merged**
