### PR TITLE
Vote for nomination of Woods, Chris and Trenner, Thomas as TSC members

### PR DESCRIPTION
**Pull request by xwang98**
I would like to nominate Chris Woods and Thomas Trenner as WAMR TSC members. They and the company contributed to the feature exception handling, and their proactive involvement and valuable advice in many WAMR technical discussions greatly helped the WAMR community.

@ttrenner @woodsmc: Could reply to this on whether or not you agree to accept the nomination?

@lum1n0us, @no1wudi, @qinxk-inter, @wei-tang, @wenyongh, @xujuntwt95329 @donghengqaz, @loganek, @yamt: As current TSC members, could you click emoji thumb up or thumb down for your vote to the nomination?

### CODE REVIEW

**Comment by ttrenner** [comment]
agree

**Comment by loganek** [comment]
I support the nomination.

**Review by loganek — APPROVED** [review]

**Comment by woodsmc** [comment]
@xwang98  Thank you. I'm honored to be nominated.

**Comment by xwang98** [comment]
I will merge it as we already received agreements from more than 50% of the TSC members.

**Pull request merged**
