### PR TITLE
Add vprintf override for android and esp-idf

### PR DESCRIPTION
**Pull request by eloparco**

### CODE REVIEW

**Comment by eloparco** [comment]
The failure in CI is for [test-wamr-ide](https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/7989934789/job/21817728323?pr=3174#logs), unrelated to the changes in the PR.

**Comment by wenyongh** [comment]
@eloparco could you also help change the document?
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#set-vprintf-callback

Currently it only mentions `Linux, Darwin, Windows and VxWorks`, we had better add Android and esp-idf also.

**Comment by wenyongh** [comment]
> The failure in CI is for [test-wamr-ide](https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/7989934789/job/21817728323?pr=3174#logs), unrelated to the changes in the PR.

Yes, the PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/3172 was submitted to fix it and is under review.

**Comment by eloparco** [comment]
>@eloparco could you also help change the document?

Sure, done

**Review by wenyongh — APPROVED** [review]

**Pull request merged**
