### PR TITLE
Disable FPU in NuttX spec test

### PR DESCRIPTION
**Pull request by no1wudi**
This will fix spec test on NuttX with #2780 , see: https://github.com/no1wudi/wasm-micro-runtime/actions/runs/6888958439

### CODE REVIEW

**Comment by yamt** [comment]
> This will fix spec test on NuttX with #2780 , see: https://github.com/no1wudi/wasm-micro-runtime/actions/runs/6888958439

what problem does this fix?

**Comment by no1wudi** [comment]
> > This will fix spec test on NuttX with #2780 , see: https://github.com/no1wudi/wasm-micro-runtime/actions/runs/6888958439
> 
> what problem does this fix?

NuttX now enabled FPU for rv-vrit by default, but current test script about risc-v is works with FPU disabled.

I plan to let CI cover more platform, such as aarch64, and existing platform with or without FPU support, but let's have quick fix first.

**Review by yamt — APPROVED** [review]
lgtm

**Comment by no1wudi** [comment]
> does this basically undo this? [apache/nuttx@61460ef](https://github.com/apache/nuttx/commit/61460efe3ca7bd4f04d28d74e874060d279af7e8)

Yes.

**Pull request merged**
