### PR TITLE
Implement load lanes opcodes for wasm

### PR DESCRIPTION
**Pull request by Zzzabiyaka**
Tested using a simple wat file while we're still setting up the testsuite

### CODE REVIEW

**Review by loganek — APPROVED** [review]
LGTM

**Review by wenyongh — APPROVED** [review]
LGTM

**Comment by Zzzabiyaka** [comment]
the failure in CI is 

```
Running: ../../../product-mini/platforms/linux/build/iwasm --heap-size=0 --repl --stack-size=10485760 /tmp/tmpersehdkx.aot
module is ....'(module
    (rec (type $f1 (func)) (type (struct (field (ref $f1)))))
    (rec (type $f2 (func)) (type (struct (field (ref $f1)))))
    (func $f (type $f2))
    (global (ref $f1) (ref.func $f))
  )'
exception is ....'type mismatch'
Writing WAST module to '/tmp/tmp_0kh_4j_.wast'
Compiling WASM to '/tmp/tmpg5mpng73.wasm'
Running: spec/interpreter/wasm -u -d /tmp/tmp_0kh_4j_.wast -o /tmp/tmpg5mpng73.wasm
Compiling '/tmp/tmpg5mpng73.wasm' to '/tmp/tmpersehdkx.aot'
```

@wenyongh I don't think it's related to my PR in any way, if you agree can we merge?

**Comment by wenyongh** [comment]
> the failure in CI is
> 
> ```
> Running: ../../../product-mini/platforms/linux/build/iwasm --heap-size=0 --repl --stack-size=10485760 /tmp/tmpersehdkx.aot
> module is ....'(module
>     (rec (type $f1 (func)) (type (struct (field (ref $f1)))))
>     (rec (type $f2 (func)) (type (struct (field (ref $f1)))))
>     (func $f (type $f2))
>     (global (ref $f1) (ref.func $f))
>   )'
> exception is ....'type mismatch'
> Writing WAST module to '/tmp/tmp_0kh_4j_.wast'
> Compiling WASM to '/tmp/tmpg5mpng73.wasm'
> Running: spec/interpreter/wasm -u -d /tmp/tmp_0kh_4j_.wast -o /tmp/tmpg5mpng73.wasm
> Compiling '/tmp/tmpg5mpng73.wasm' to '/tmp/tmpersehdkx.aot'
> ```
> 
> @wenyongh I don't think it's related to my PR in any way, if you agree can we merge?

Yes, please merge. BTW, I re-ran the CI.

**Pull request merged**
