### PR TITLE
Add wamr to esp-idf components registry.

### PR DESCRIPTION
**Pull request by donghengqaz**
This PR is for the main branch, but only the released branch will be pushed into Espressif component registry.

### CODE REVIEW

**Comment by donghengqaz** [comment]
Hi @wenyongh, when I run the example in the main branch, I found the interpreter mode works well, but AOT mode shows error as follows:

```
E (344) wamr: Error in wasm_runtime_load: AOT module load failed: unexpect end
```

Do you know something about this?

**Comment by wenyongh** [comment]
> Hi @wenyongh, when I run the example in the main branch, I found the interpreter mode works well, but AOT mode shows error as follows:
> 
> ```
> E (344) wamr: Error in wasm_runtime_load: AOT module load failed: unexpect end
> ```
> 
> Do you know something about this?

Did you build wamrc from the main branch and use it to generate the AOT file again? The AOT file format of main is different from the format of 1.3.x now.

**Comment by donghengqaz** [comment]
> > Hi @wenyongh, when I run the example in the main branch, I found the interpreter mode works well, but AOT mode shows error as follows:
> > ```
> > E (344) wamr: Error in wasm_runtime_load: AOT module load failed: unexpect end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you know something about this?
> 
> Did you build wamrc from the main branch and use it to generate the AOT file again? The AOT file format of main is different from the format of 1.3.x now.

Thanks, I will try this.

**Comment by wenyongh** [comment]
@donghengqaz there is a CI coding guideline check failure, could you help fix it? It seems this line is too long:
```C
void *buf_origin = heap_caps_malloc(size + 4 + sizeof(uintptr_t), mem_caps);
```
It was fixed in another PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/3288

**Comment by donghengqaz** [comment]
> @donghengqaz there is a CI coding guideline check failure, could you help fix it? It seems this line is too long:
> 
> ```c
> void *buf_origin = heap_caps_malloc(size + 4 + sizeof(uintptr_t), mem_caps);
> ```
> 
> It was fixed in another PR #3288

OK, and I will fix the AOT file data format error.

**Review by wenyongh — APPROVED** [review]

**Pull request merged**
