### PR TITLE
Return error when shutdown() fails

### PR DESCRIPTION
**Pull request by loganek**
Related issue: https://github.com/bytecodealliance/wasm-micro-runtime/issues/2787

### CODE REVIEW

**Review by yamt — APPROVED** [review]
lgtm

**Comment by loganek** [comment]
@wenyongh could you have a look please? Thanks a lot

**Comment by wenyongh** [comment]
> @wenyongh could you have a look please? Thanks a lot

LGTM. Should I merge it now?

**Review by wenyongh — APPROVED** [review]
LGTM

**Pull request merged**
