### PR TITLE
document the summary of two pthread implementations

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by wenyongh** [comment]
Thanks @yamt ! We are just wondering how to add the document of wasi-threads, and add an item to the [Key features](https://github.com/bytecodealliance/wasm-micro-runtime#key-features) list of README.md. How about we adding a line in README.md after `Multi-thread, pthread APIs and thread management` by referring to your document:
`- [wasi-threads](./doc/pthread_impls.md#wasi-threads-new), ref to [document](./doc/pthread_impls.md#wasi-threads-new) and [sample](samples/wasi-threads)`

And provide more detail document about wasi-threads in the future if needed.

**Review by wenyongh — APPROVED** [review]

**Comment by yamt** [comment]
> Thanks @yamt ! We are just wondering how to add the document of wasi-threads, and add an item to the [Key features](https://github.com/bytecodealliance/wasm-micro-runtime#key-features) list of README.md. How about we adding a line in README.md after `Multi-thread, pthread APIs and thread management` by referring to your document: `- [wasi-threads](./doc/pthread_impls.md#wasi-threads-new), ref to [document](./doc/pthread_impls.md#wasi-threads-new) and [sample](samples/wasi-threads)`

it makes sense. do you want me to do it in this PR?

**Comment by wenyongh** [comment]
> > Thanks @yamt ! We are just wondering how to add the document of wasi-threads, and add an item to the [Key features](https://github.com/bytecodealliance/wasm-micro-runtime#key-features) list of README.md. How about we adding a line in README.md after `Multi-thread, pthread APIs and thread management` by referring to your document: `- [wasi-threads](./doc/pthread_impls.md#wasi-threads-new), ref to [document](./doc/pthread_impls.md#wasi-threads-new) and [sample](samples/wasi-threads)`
> 
> it makes sense. do you want me to do it in this PR?

Yes, appreciated!

**Comment by yamt** [comment]
> > > Thanks @yamt ! We are just wondering how to add the document of wasi-threads, and add an item to the [Key features](https://github.com/bytecodealliance/wasm-micro-runtime#key-features) list of README.md. How about we adding a line in README.md after `Multi-thread, pthread APIs and thread management` by referring to your document: `- [wasi-threads](./doc/pthread_impls.md#wasi-threads-new), ref to [document](./doc/pthread_impls.md#wasi-threads-new) and [sample](samples/wasi-threads)`
> > 
> > 
> > it makes sense. do you want me to do it in this PR?
> 
> Yes, appreciated!

done

**Pull request merged**
