### PR TITLE
Add get_native_lib that is used by iwasm to load  wasi-nn as a native library

### PR DESCRIPTION
**Pull request by rodjjo**
##  What
* When it was running the example from `wasm-micro-runtime/core/iwasm/libraries/wasi-nn` there was an error where iwasm was not able to register the functions into the wasm vm.
* Fix a typo in `core/iwasm/libraries/wasi-nn/test/utils.c`

## Why
We need get_native_lib in order to use --native-lib=path-to-lib.so missing for this wasi-nn library.

## Note
I kept get_wasi_nn_export_apis as it was as i did not know where it is used.

Now it runs:
image

### CODE REVIEW

**Comment by rodjjo** [comment]
image
I guess we have an unstable test there. I just included a empty line (I would never affect the tests).

**Comment by wenyongh** [comment]
> image I guess we have an unstable test there. I just included a empty line (I would never affect the tests).

Yes, the CI sometimes encounters error, e.g. failed to download packages. I re-ran it and now it works.

**Review by wenyongh — APPROVED** [review]
LGTM

**Comment by lum1n0us** [comment]
Please test with #3820

By design, `--native-lib` is not required.

**Review by lum1n0us — CHANGES_REQUESTED** [review]
Please test with https://github.com/bytecodealliance/wasm-micro-runtime/pull/3820

**Comment by rodjjo** [comment]
@lum1n0us I made questions/suggestions on your PR.
I'm closing this one due your changes there.

**Pull request closed without merging**
