### PR TITLE
Remove unused JitBitmap

### PR DESCRIPTION
**Pull request by yamt**
fixes: https://github.com/bytecodealliance/wasm-micro-runtime/issues/2754

### CODE REVIEW

**Comment by yamt** [comment]
windows ci failure seems unrelated. i filed an issue: https://github.com/bytecodealliance/wasm-micro-runtime/issues/2776

**Comment by wenyongh** [comment]
> windows ci failure seems unrelated. i filed an issue: #2776

@yamt shall I re-run the CI?

**Comment by yamt** [comment]
> > windows ci failure seems unrelated. i filed an issue: #2776
> 
> @yamt shall I re-run the CI?

yes please

**Review by wenyongh — COMMENTED** [review]
LGTM

**Pull request merged**
