### PR TITLE
Upgrade toolkits

### PR DESCRIPTION
**Pull request by wenyongh**
Upgrade the version of related toolkits:
- upgrade llvm to 15.0
- upgrade wasi-sdk to 19.0
- upgrade emsdk to 3.1.28
- upgrade wabt to 1.0.31
- upgrade binaryen to 111

And upgrade the CI scripts, sample workload build scripts, Dockerfiles, and documents.

### CODE REVIEW

**Comment by yamt** [comment]
> upgrade wasi-sdk to 16.0

FYI, wasi-sdk 16 had an issue related to ctors. https://github.com/WebAssembly/wasi-libc/pull/328
it affects malloc/free exports we use to use libc heap.
it has been fixed by wasi-sdk 17.

**Comment by wenyongh** [comment]
> > upgrade wasi-sdk to 16.0
> 
> FYI, wasi-sdk 16 had an issue related to ctors. [WebAssembly/wasi-libc#328](https://github.com/WebAssembly/wasi-libc/pull/328) it affects malloc/free exports we use to use libc heap. it has been fixed by wasi-sdk 17.

Yes, it would be better to use the higher version, wasi-sdk-17.0 works on Ubuntu-22.04, but it requires higher version of GLIBC on Ubuntu-20.04:
 ```bash
$ /opt/wasi-sdk-17.0/bin/clang -O3 -o test.wasm main.c
/opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/wasi-sdk-17.0/bin/clang)
/opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/wasi-sdk-17.0/bin/clang)
/opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/wasi-sdk-17.0/bin/clang)
```
Do you have any suggestions?

**Comment by yamt** [comment]
> > > upgrade wasi-sdk to 16.0
> > 
> > 
> > FYI, wasi-sdk 16 had an issue related to ctors. [WebAssembly/wasi-libc#328](https://github.com/WebAssembly/wasi-libc/pull/328) it affects malloc/free exports we use to use libc heap. it has been fixed by wasi-sdk 17.
> 
> Yes, it would be better to use the higher version, wasi-sdk-17.0 works on Ubuntu-22.04, but it requires higher version of GLIBC on Ubuntu-20.04:
> 
> ```shell
> $ /opt/wasi-sdk-17.0/bin/clang -O3 -o test.wasm main.c
> /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> ```
> 
> Do you have any suggestions?

we can wait for the next wasi-sdk, which is supposed to have a build for bionic.
https://github.com/WebAssembly/wasi-sdk/issues/284#issuecomment-1378708664

**Comment by wenyongh** [comment]
> > > FYI, wasi-sdk 16 had an issue related to ctors. [WebAssembly/wasi-libc#328](https://github.com/WebAssembly/wasi-libc/pull/328) it affects malloc/free exports we use to use libc heap. it has been fixed by wasi-sdk 17.
> > 
> > 
> > Yes, it would be better to use the higher version, wasi-sdk-17.0 works on Ubuntu-22.04, but it requires higher version of GLIBC on Ubuntu-20.04:
> > ```shell
> > $ /opt/wasi-sdk-17.0/bin/clang -O3 -o test.wasm main.c
> > /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> > /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> > /opt/wasi-sdk-17.0/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/wasi-sdk-17.0/bin/clang)
> > ```
> >   
> > Do you have any suggestions?
> 
> we can wait for the next wasi-sdk, which is supposed to have a build for bionic. [WebAssembly/wasi-sdk#284 (comment)](https://github.com/WebAssembly/wasi-sdk/issues/284#issuecomment-1378708664)

Sounds good, I found that wasi-sdk has recently release [was-sdk-18](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-18) and [wasi-sdk-19](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-19):
- wasi-sdk-18 doesn't release any binary files to install yet, and it mentions that `NOTE: This release changes the behavior of malloc in programs compiled with -Wl,--initial-memory to use memory.grow rather than using all the statically-allocated memory. This will be fixed in wasi-sdk-19`, sounds that this version has defect or bug
- wasi-sdk-19 has binary files, I tried installing and using [wasi-sdk-19.0-linux.tar.gz](https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk-19.0-linux.tar.gz), it works in Ubuntu-20.04, the issue of requiring GLIBC higher version support is fixed.

So I think we had better use wasi-sdk-19.0, let's test more.

**Comment by yamt** [comment]
how about core/iwasm/libraries/wasi-nn/test/Dockerfile

**Comment by wenyongh** [comment]
> how about core/iwasm/libraries/wasi-nn/test/Dockerfile

PR #1922 is updating wasi-nn, I left a comment to ask upgrading the version of wasi-sdk in the Dockerfile.

**Review by yamt — APPROVED** [review]

**Pull request merged**
