### PR TITLE
Refactor go binding

### PR DESCRIPTION
**Pull request by wenyongh**
Refactor the APIs of runtime, module and instance,
refactor the sample, and update the related scripts.
Rename the folder name to language-bindings and samples.
To update the document soon.

### CODE REVIEW

**Comment by lum1n0us** [comment]
is `core/iwasm/interpreter/wasm_interp_fast_test.c` necessary?

**Comment by wenyongh** [comment]
> is `core/iwasm/interpreter/wasm_interp_fast_test.c` necessary?

Just to test code guideline, already removed.

**Comment by lum1n0us** [comment]
`bindings/go` or `language-bindings/go` ?

**Comment by wenyongh** [comment]
> `bindings/go` or `language-bindings/go` ?
> 
> language-bindings/go

language-bindings/go

**Pull request merged**
