### PR TITLE
Update version number to 1.3.2 and update release notes

### PR DESCRIPTION
**Pull request by wenyongh**

### CODE REVIEW

**Comment by wenyongh** [comment]
Hi @yamt, @loganek and @no1wudi, recently we had many fixings and enhancements after the last release, I think it may be a good time to release 1.3.2, and if needed, we can wait some time and release 1.3.3 again. And after that, I will merge the exception handling and GC (garbage collection) features from branch dev/exce_handling and dev/gc_refactor, which are big changes with AOT ABI broken and we should then release 2.0.0 in the future. How do you think?

**Comment by loganek** [comment]
Thanks, sounds reasonable to me. Do you think we'll need 1.3.3 or should we go straight to 2.0.0 with exception support? Also, we were talking with @xwang98 about adding wasm64 support, which possibly (but I'm not 100% sure) would break the AOT ABI too. Should we put 2.0.0 release on hold until we have that feature?

**Comment by wenyongh** [comment]
> Thanks, sounds reasonable to me. Do you think we'll need 1.3.3 or should we go straight to 2.0.0 with exception support? Also, we were talking with @xwang98 about adding wasm64 support, which possibly (but I'm not 100% sure) would break the AOT ABI too. Should we put 2.0.0 release on hold until we have that feature?

Welcome. For 1.3.3, I am not very sure whether to release it or not, seems most issues were fixed and current version is relatively stable, maybe we can do more tests before releasing 1.3.2 and bump to 2.0.0 after that. Looking forward to the input from @yamt and @no1wudi.

For memory64, yes, definitely it breaks the AOT ABI, @TianlongLiang is summarizing the changes and will open an issue for discussion. And yes, we had better merge the ABI changes from GC and memory64 together before 2.0.0.

BTW, we can also resolve some historical issues mentioned in https://github.com/bytecodealliance/wasm-micro-runtime/issues/2530.

**Comment by no1wudi** [comment]
> For memory64, yes, definitely it breaks the AOT ABI, @TianlongLiang is summarizing the changes and will open an issue for
> discussion. And yes, we had better merge the ABI changes from GC and memory64 together before 2.0.0.

For me, I agree to wait for memroy64 to avoid break AOT ABI again after GC

**Comment by yamt** [comment]
exception-handling branch seems to implement a bit old version of the proposal. (opcodes are quite different from the latest proposal.)
is it something we consider ready for main? (just asking, i myself have no strong opinion)

anyway, it's a good idea to have another 1.3.x release.

**Comment by loganek** [comment]
> exception-handling branch seems to implement a bit old version of the proposal. (opcodes are quite different from the latest proposal.) is it something we consider ready for main? (just asking, i myself have no strong opinion)

That's a valid concern, and it was discussed recently. Overall the idea was to merge the exceptions branch as soon as possible but have it optional and marked as unstable. The main reason for that was that it's difficult to maintain the branch and keep resolving conflicts.

**Comment by fredldotme** [comment]
I am regularly merging the exception handing branch and keep it freshly updated on top of my own personal changes, so it helps to have it.

I have thrown a bunch of Clang flags at this and have not come to a configuration where the right opcodes do the right thing and TRY labels are found, which leads me to believe that upstream LLVM 17 just cannot do it due to a revert or something else getting adapted.

It would be nice to get input on which binaries were thrown at it using which compilers and flags.

**Comment by wenyongh** [comment]
> > exception-handling branch seems to implement a bit old version of the proposal. (opcodes are quite different from the latest proposal.) is it something we consider ready for main? (just asking, i myself have no strong opinion)
> 
> That's a valid concern, and it was discussed recently. Overall the idea was to merge the exceptions branch as soon as possible but have it optional and marked as unstable. The main reason for that was that it's difficult to maintain the branch and keep resolving conflicts.

Yes, one is for code maintenance, the other is it may let more developers try it. For the support for other running modes like fast-interp, AOT and fast-jit, we can keep them developed in the development branch, maybe a new branch or just using dev/exce_handling.

**Comment by loganek** [comment]
How about we merge the dev/exce_handling branch for 1.3.2 (or 1.3.3) but mark it as highly experimental then? Looks like we won't have 2.0.0 any time soon and keeping the branch with main looks like a significant overhead for developers.

**Comment by wenyongh** [comment]
> How about we merge the dev/exce_handling branch for 1.3.2 (or 1.3.3) but mark it as highly experimental then? Looks like we won't have 2.0.0 any time soon and keeping the branch with main looks like a significant overhead for developers.

It is good to me, I will try to merge the exception handling branch to main soon.

**Comment by loganek** [comment]
@wenyongh is there any pending PR to get that merged or we're good to go?

**Comment by wenyongh** [comment]
> @wenyongh is there any pending PR to get that merged or we're good to go?

Hi, @xujuntwt95329 is fixing issue https://github.com/bytecodealliance/wasm-micro-runtime/issues/3061 and maybe submit the PR soon. But we don't need to wait for that to create the release I think, I will update the release notes in this PR and merge it, and do some tests, if things go good, let's create the release. Is that OK for you?

**Comment by loganek** [comment]
I think that's a good approach. For my team specifically it's not a problem to re-compile AOT binaries and we'd be migrating to 2.0 for various other reasons, but I can see some usecases where this is important.
I'd suggest though to keep track on those usecases so we can come up with a deprecation plan. Optionally, we can set a support date now (e.g. 1year) and announce it.

**Comment by no1wudi** [comment]
That's good, and should we have a schedule about it?  Such as the release/1.3.x will reach the end of its lifecycle in 2025.

**Comment by wenyongh** [comment]
> That's good, and should we have a schedule about it? Such as the release/1.3.x will reach the end of its lifecycle in 2025.

Is it a little long to maintain it until the end of 2025, how about the end of 2024? One is that most of the issues (if found) should have been resolved, the other is that developer should have enough time to migrate to the new version. And after that, if needed, we can maintain more time.

**Comment by no1wudi** [comment]
It's OK. The specific time is not important; what’s crucial is to remind users to migrate as soon as possible while leaving them a little room.

**Comment by loganek** [comment]
I think one year sounds reasonable. I'm not sure what'd be the best way to notify users to upgrade though; I assume not everybody reads release notes. Perhaps we can add a big CMake warning in the 1.3.x branch to remind developers to upgrade?

**Pull request merged**
